# .github/workflows/ci.yml
name: Static code analysis and container build
on:
  push:          { branches: [dev] }
  pull_request:  { branches: [master] }

permissions:
  contents: read
  id-token: write

env:
  IMAGE_NAME: mlops-a3-inference
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  
jobs:
  lint:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          { python-version: '3.11' }

      - name: Install Python dependencies
        run: pip install -r requirements.txt flake8

      - name: Execute static code analysis
        run: flake8 src/ --max-line-length=120

  build-sign-push:
    name: Build, Sign and Push Docker Image
    needs: lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg HF_MODEL_NAME="${{ secrets.HF_MODEL_NAME }}" \
            -t $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }} \
            -t $DOCKERHUB_USERNAME/$IMAGE_NAME:dev-latest .

      - name: Push Docker Image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:dev-latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Immutable Image using GitHub OIDC
        run: |
          cosign sign --yes \
            $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}
      
